version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=kanbar
    volumes:
      - pg_data:/bitnami/postgresql
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
